# valleymind_utils/common_misspellings.py

# common_misspellings.py

# A dictionary of common misspellings and their corrected forms
COMMON_MISSPELLINGS = {
    "definately": "definitely",
    "teh": "the",
    "recieve": "receive",
    "adress": "address",
    "occured": "occurred",
    "untill": "until",
    "seperated": "separated",
    "goverment": "government",
    "occassion": "occasion",
    "enviroment": "environment",
    "neccessary": "necessary",
    "publically": "publicly",
    "wich": "which",
    "becouse": "because",
    "acommodate": "accommodate",
    "tomatos": "tomatoes",
    "existance": "existence",
    "happend": "happened",
    "emmediately": "immediately",
    "finnaly": "finally",
    "wierd": "weird",
    "responce": "response",
    "calender": "calendar",
    "managment": "management",
    "comming": "coming",
    "realy": "really",
    "writting": "writing",
    "beleive": "believe",
    "arguement": "argument",
    "begining": "beginning",
    "concious": "conscious",
    "succesful": "successful",
    "buisness": "business",
    "truely": "truly",
    "inconvienent": "inconvenient",
    "desparate": "desperate",
    "embarass": "embarrass",
    "millenium": "millennium",
    "remeber": "remember",
    "neice": "niece",
    "acquaintence": "acquaintance",
    "concieve": "conceive",
    "thier": "their",
    "tommorow": "tomorrow",
    "littel": "little",
    "freind": "friend",
    "havent": "haven’t",
    "doesnt": "doesn’t",
    "isnt": "isn’t",
    "woudnt": "wouldn’t",
    "alot": "a lot",
    "dont": "don’t",
    "cant": "can’t",
    "shouldnt": "shouldn’t",
    "writen": "written",
    "knowlege": "knowledge",
    "lenght": "length",
    "interupt": "interrupt",
    "seige": "siege",
    "suprise": "surprise"
}

def correct_spelling(word):
    return COMMON_MISSPELLINGS.get(word.lower(), word)